apiVersion: v1
kind: Service
metadata:
  name: vue-bg-svc
spec:
  type: ClusterIP
  selector:
    app: vue-bg
    version: blue    # 초기에는 blue 쪽으로만 트래픽 전송
  ports:
    - port: 8000
      targetPort: 80