apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-green-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-bg
      version: green
  template:
    metadata:
      labels:
        app: vue-bg
        version: green
    spec:
      containers:
        - name: vue-container
          image: limu810/k8s-vue-ing:v2
          ports:
            - containerPort: 80
